### ISSUE TITLE
微信小程序自定义组件中无法播放，一直报错 canvas not found，传了组件id和组件实例

### ISSUE THREAD

**Issue by firefly66** [svga/svgaplayer-weapp#10]
微信小程序自定义组件中无法播放，一直报错 canvas not found，传了组件id和组件实例，代码片段https://developers.weixin.qq.com/s/oNanmHme7pve

**Comment by emmenisme** [comment]
组件的执行顺序问题，如果是 v-if 的，试试 nexttick

**Comment by firefly66** [comment]
没有使用v-if，组件是一开始就一直渲染的，画布已经渲染出来了，然后再点的播放，报canvas not found

**Comment by emmenisme** [comment]
我这拿你的代码可以播放。没有问题

**Comment by firefly66** [comment]
我的天，这也太奇怪了，一样的代码，昨天居然不行，这是什么鬼，让我试了好久，啊～ 确实可以
