### ISSUE TITLE
loop 非0 ，动画还是无限循环播放

### ISSUE THREAD

**Issue by wtz** [svga/svgaplayer-weapp#16]
await player.setVideoItem(videoItem);
      player.startAnimation();

      player.loop = 100;
      player.fillMode = "Forward";

**Comment by PonyCui** [comment]
player.loop = 100; -> player.loops = 100;

**Comment by wtz** [comment]
@PonyCui  改成loops 还是一样的，用的Mac os 系统。
主要代码如下：

      const parser = new Parser();
      const player = new Player;
      await player.setCanvas('#demoCanvas');
      
      const videoItem = await parser.load("https://xxx.com/kingset.svga");
      await player.setImage('https://xxx.com/2/start.png', '99');
      player.setText({
        text: 'Pony send Kitty flowers.',
        size: 28,
        color: "white",
        offset: {y: 10}
      }, 'banner');
      await player.setVideoItem(videoItem);
      player.startAnimation();

      // loops 非0，动画还是循环播放
      player.loops = 100;
      player.fillMode = "Forward";

**Comment by wtz** [comment]
还有监听动画完成函数未执行
player.onFinished(()=>{
        console.log('监听动画完成'); // 动画播放完成后，并没有执行
      });
