### ISSUE TITLE
大佬，能否支持下音频播放,

### ISSUE THREAD

**Issue by emmenisme** [svga/svgaplayer-weapp#7]
首先感谢作者的无私奉献！大爱无疆

我是上次给你提意见的，“组件内无法使用的问题”。
感谢您，更新了代码！！

能否使用wx.playVoice，支持音频播放，我也不是很确定，我对小程序也不熟悉！

感谢！！

**Comment by PonyCui** [comment]
小程序的声音 API 过于复杂，需要占用太多时间去研究，暂时不考虑实现。

**Comment by emmenisme** [comment]
能够在现有基础上面，处理下音频的报错
现在是音频作为图片解析了，会报错！
做下类型判断，自动过掉音频，这样同一个swag文件都能在各端使用了，现在的话，只能将svga音频去掉，以兼容多端

感谢！！

**Comment by PonyCui** [comment]
好的，这个没问题。

**Comment by PonyCui** [comment]
[](https://camo.githubusercontent.com/76607ece7914832373b2e7d5022ad84a9a5adb5d9432f30f2a26947facf87f48/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f506f6e794375692f706f6e796375692e6769746875622e696f406d61737465722f636f6e746163742e706e67)
